spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  mvc:
    favicon:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.20.57:3306/springbootdemo?useSSL=false
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
    enabled: false
server:
  tomcat:
    uri-encoding: UTF-8
logging:
  file: C:\log\h2.log
  level:
    root: info
