spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.20.57:3306/springbootdemo?useSSL=false
    username: root
    password: root
server:
  tomcat:
    uri-encoding: UTF-8
logging:
  file: C:\log\jpa.log
  level:
    root: info
